### ISSUE TITLE
Valores dos blocos não estão sendo alterados.

### ISSUE THREAD

**Issue by avnermax** [Mosaicode/mosaicode#32]
Após rodar um código uma vez, os valores dentro de um ou mais blocos, que foram alterados, não são redefinidos. Fica sempre rodando os valores que foram definidos antes da primeira execução.

**Comment by flschiavoni** [comment]
A geração de código ocorria no objeto Bloco do Diagrama fazendo a substituição da tag $prop[name]$ pelo valor da propriedade. Logo, na segunda geração, o código do bloco não possuia mais a tag $prop[name]$. A solução é clonar os trechos de código do objeto Bloco e alterar o código na cópia do código e não no código original.
